matrix:
  include:
    - language:  php
      php: 5.6 
      before_script:
          - find . -type f -name *.php | xargs -n1 php -l
      script:        
          - cd ${TRAVIS_BUILD_DIR}
          - pwd
      after_success:
          - cd ${TRAVIS_BUILD_DIR}
          - ls -latr
      after_failure:
          - cd ${TRAVIS_BUILD_DIR}
          - ls -latr
    
    - language: python
      python: 2.7
      script:
        - pwd
        
    - language: markdown
      script:
        - gem install mdl
        - MDLWARNINGS="MD003,MD004,MD005,MD006,MD007,MD008,MD009,MD010,MD011,MD012,MD014,MD018,MD019,MD020,MD021,MD022,MD023,MD024,MD027,MD028,MD029,MD030,MD031,MD032,MD033,MD034,MD035,MD036,MD038,MD039"
        - mdl -r $MDLWARNINGS *.md docs/fr_FR/*.md >/dev/null
    

