matrix:
  include:
    - language:  php
      php: 5.6 
      before_script:
          - find . -type f -name *.php | xargs -n1 php -l
      script:        
          - cd ${TRAVIS_BUILD_DIR}
          - pwd
      after_success:
          - cd ${TRAVIS_BUILD_DIR}
          - ls -latr
      after_failure:
          - cd ${TRAVIS_BUILD_DIR}
          - ls -latr
    
    - language: python
      python: 2.7
      script:
        - pwd
        
    - language: markdown
      script:
        - gem install mdl
        - for file in *.md docs/fr_FR/*.md;do  mdl $file;done
        - mdl *.md docs/fr_FR/*.md >/dev/null
    

